package constants

const (
	ROOT          = "code-shooting"
	NODE          = "app"
	APP_NAME      = "name"
	APP_NAMESPACE = "namespace"

	DATABASE_ES                  = "databases.es"
	DATABASE_PG                  = "databases.postgres"
	DATABASE_REDIS               = "databases.redis"
	EVENT_CENTER                 = "eventCenter"
	FILE_TRANSFER                = "fileTransfer"
	GRPC_CLIENT                  = "grpcClient"
	GRPC_SERVER                  = "grpcServers"
	HTTP_CLIENT                  = "httpclient"
	LEADER_ELECTION              = "leaderElection"
	LOG                          = "log"
	LOG_LEVEL                    = "log.level"
	LOG_ROTATE_CONFIG            = "log.rotateConfig"
	LOG_ROTATE_CONFIG_MAXSIZE    = "log.rotateConfig.maxSize"
	LOG_ROTATE_CONFIG_MAXBACKUPS = "log.rotateConfig.maxBackups"
	LOG_ROTATE_CONFIG_MAXAGE     = "log.rotateConfig.maxAge"
	LOG_ROTATE_CONFIG_COMPRESS   = "log.rotateConfig.compress"
	MESSAGEBUS_KAFKA             = "messagebus.kafka"
	NETCONF_CLIENT               = "netconfClient"
	OBSERVABILITY_METRICS        = "observability.metrics"
	OBSERVABILITY_TRACING        = "tracing"
	REST_SERVER                  = "rest-servers"
	SNMP_NMS                     = "snmp.nms"
	ZOOKEEPER                    = "zookeeper"
	SERVICE_CENTER_MSB           = "serviceCenter.msb"
	SCENE                        = "scene"
	SERVICE_FOR_PICT_SCENE       = "pict"
)
