{
 "title": "personal",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "userId", "label": "用户工号", "query": "10146152" },
   { "name": "cycleTxt", "label": "时间范围", "query": "一周" }
  ]
 },
 "panels": [
  {
   "title": "我最近$cycleTxt内系统访问次数",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(id) from range_request_pos where ((user_id = '$userId') and ($__timeFrom() <= range_request_pos.request_time)) group by user_id ;"
    }
   ]
  },
  {
   "title": "我最近$cycleTxt内缺陷分类平均命中率雷达图",
   "type": "snuids-radar-panel",
   "gridPos": { "h": 11, "w": 8, "x": 4, "y": 0 },
   "targets": [
    {
     "rawSql": "select now() as \"time\", defect, round(sum(accuracyrate)/count(defect),2) from cs_context.cs_target_defect_accuracy('$userId', $__timeFrom()::timestamp) \ngroup by defect;\n"
    }
   ]
  },
  {
   "title": "我最近$cycleTxt内缺陷分类平均命中率",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "select defect, sum(accuracyrate)/count(defect) as \"缺陷分类平均命中率\" from cs_context.cs_target_defect_accuracy('$userId', $__timeFrom()) group by defect;"
    }
   ]
  },
  {
   "title": "我最近$cycleTxt内贡献的靶子数",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from (select count(target_id) from ring_num_pos where ((owner_id = '$userId') and ($__timeFrom() <= create_time)) group by target_id) as temp_table ;"
    }
   ]
  },
  {
   "title": "我最近$cycleTxt内在各靶场的打靶次数分布",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select range.name as \"靶场名称\", count(shooting_record_pos.id) as \"打靶次数\" from shooting_record_pos, cs_context.range where ((shooting_record_pos.user_id = '$userId') and (shooting_record_pos.range_id = range.id) and ($__timeFrom() <= shooting_time)) group by range.\"name\" ;"
    }
   ]
  },
  {
   "title": "我最近$cycleTxt内各语言的打靶次数分布",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select language as \"编程语言\", count(shooting_record_pos.id) as \"打靶次数\" from shooting_record_pos where ((shooting_record_pos.user_id = '$userId') and ($__timeFrom() <= shooting_time)) group by language ;"
    }
   ]
  },
  {
   "title": "我最近$cycleTxt内打靶总次数",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(id) from shooting_record_pos where ((user_id = '$userId') and ($__timeFrom() <= shooting_time)) group by user_id;"
    }
   ]
  }
 ]
}