{
 "title": "靶标规范覆盖厚度",
 "time": { "from": "2023-01-29T10:51:07.408Z", "to": "2023-01-31T10:51:07.408Z" },
 "panels": [
  {
   "title": "C&C++语言规范覆盖厚度",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select defect_pos.defect_class, defect_pos.defect_subclass, defect_pos.defect_describe, \ncase when sum(defect_num) isnull then 0 else sum(defect_num) end as defect_thick \nfrom (\n  select * \n  from defect_pos \n  where language='C&C++' or language='通用'\n)defect_pos left outer join (select * from target_defect_stat_pos \n  where target_defect_stat_pos.target_id in (\n    select target_pos.id\n    from target_pos\n    where target_pos.language in ('C', 'C++')\n  )\n)target_defect_stat_pos \non defect_pos.defect_id=target_defect_stat_pos.defect_id\ngroup by defect_pos.defect_class,defect_pos.defect_subclass, defect_pos.defect_describe\norder by defect_thick desc"
    }
   ]
  },
  {
   "title": "Java语言规范覆盖厚度",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select defect_pos.defect_class, defect_pos.defect_subclass, defect_pos.defect_describe, \ncase when sum(defect_num) isnull then 0 else sum(defect_num) end as defect_thick \nfrom (\n  select * \n  from defect_pos \n  where language='Java' or language='通用'\n)defect_pos left outer join (select * from target_defect_stat_pos \n  where target_defect_stat_pos.target_id in (\n    select target_pos.id\n    from target_pos\n    where target_pos.language = 'Java'\n  )\n)target_defect_stat_pos \non defect_pos.defect_id=target_defect_stat_pos.defect_id\ngroup by defect_pos.defect_class,defect_pos.defect_subclass, defect_pos.defect_describe\norder by defect_thick desc"
    }
   ]
  },
  {
   "title": "Go语言规范覆盖厚度",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select defect_pos.defect_class, defect_pos.defect_subclass, defect_pos.defect_describe, \ncase when sum(defect_num) isnull then 0 else sum(defect_num) end as defect_thick \nfrom (\n  select * \n  from defect_pos \n  where language='Go' or language='通用'\n)defect_pos left outer join (select * from target_defect_stat_pos \n  where target_defect_stat_pos.target_id in (\n    select target_pos.id\n    from target_pos\n    where target_pos.language = 'Go'\n  )\n)target_defect_stat_pos \non defect_pos.defect_id=target_defect_stat_pos.defect_id\ngroup by defect_pos.defect_class,defect_pos.defect_subclass, defect_pos.defect_describe\norder by defect_thick desc"
    }
   ]
  },
  {
   "title": "JavaScript语言规范覆盖厚度",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "select defect_pos.defect_class, defect_pos.defect_subclass, defect_pos.defect_describe, \ncase when sum(defect_num) isnull then 0 else sum(defect_num) end as defect_thick \nfrom (\n  select * \n  from defect_pos \n  where language='JavaScript' or language='通用'\n)defect_pos left outer join (select * from target_defect_stat_pos \n  where target_defect_stat_pos.target_id in (\n    select target_pos.id\n    from target_pos\n    where target_pos.language = 'JavaScript'\n  )\n)target_defect_stat_pos \non defect_pos.defect_id=target_defect_stat_pos.defect_id\ngroup by defect_pos.defect_class,defect_pos.defect_subclass, defect_pos.defect_describe\norder by defect_thick desc"
    }
   ]
  },
  {
   "title": "Python语言规范覆盖厚度",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "select defect_pos.defect_class, defect_pos.defect_subclass, defect_pos.defect_describe, \ncase when sum(defect_num) isnull then 0 else sum(defect_num) end as defect_thick \nfrom (\n  select * \n  from defect_pos \n  where language='Python' or language='通用'\n)defect_pos left outer join (select * from target_defect_stat_pos \n  where target_defect_stat_pos.target_id in (\n    select target_pos.id\n    from target_pos\n    where target_pos.language = 'Python'\n  )\n)target_defect_stat_pos \non defect_pos.defect_id=target_defect_stat_pos.defect_id\ngroup by defect_pos.defect_class,defect_pos.defect_subclass, defect_pos.defect_describe\norder by defect_thick desc"
    }
   ]
  },
  {
   "title": "TypeScript语言规范覆盖厚度",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "select defect_pos.defect_class, defect_pos.defect_subclass, defect_pos.defect_describe, \ncase when sum(defect_num) isnull then 0 else sum(defect_num) end as defect_thick \nfrom (\n  select * \n  from defect_pos \n  where language='TypeScript' or language='通用'\n)defect_pos left outer join (select * from target_defect_stat_pos \n  where target_defect_stat_pos.target_id in (\n    select target_pos.id\n    from target_pos\n    where target_pos.language = 'TypeScript'\n  )\n)target_defect_stat_pos \non defect_pos.defect_id=target_defect_stat_pos.defect_id\ngroup by defect_pos.defect_class,defect_pos.defect_subclass, defect_pos.defect_describe\norder by defect_thick desc"
    }
   ]
  }
 ]
}