{
 "title": "靶标规范覆盖率",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "institute", "query": "无线研究院" },
   { "name": "center_name", "query": "虚拟化研发中心" },
   { "name": "department", "query": "虚拟化五部" },
   { "name": "target_name", "query": "公司级示范靶子Go" }
  ]
 },
 "panels": [
  { "title": "靶标规范覆盖率", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$institute规范覆盖率",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "select defect_num_of_inst.institute, defect_num_of_inst.center_name, (defect_num_of_inst.defect_num/sum_num_of_language) * 100 as defect_rate\nfrom(\n  select count(DISTINCT defect_id) as defect_num, institute, center_name\n  from target_defect_stat_pos, target_pos, user_pos\n  where target_defect_stat_pos.target_id = target_pos.id and target_pos.owner = user_pos.id and institute='$institute'\n  group by institute, center_name\n) as defect_num_of_inst,(\n  select center_name, sum(defect_num_of_language)+119 as sum_num_of_language\n  from(\n    select DISTINCT case when language = 'C' or language = 'C++' then 'C&C++' else language end as language, center_name\n    from target_pos, user_pos\n    where target_pos.owner = user_pos.id and institute='$institute'\n  ) as language_in_center, (\n    select language,count(defect_id) as defect_num_of_language\n    from defect_pos\n    group by language\n  ) as defect_stat_of_language\n  where language_in_center.language=defect_stat_of_language.language\n  group by center_name\n) as all_num_of_inst\nwhere defect_num_of_inst.center_name=all_num_of_inst.center_name\norder by defect_rate desc"
    }
   ]
  },
  {
   "title": "$center_name规范覆盖率",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "select defect_num_of_inst.institute, defect_num_of_inst.center_name, defect_num_of_inst.department, (defect_num_of_inst.defect_num/sum_num_of_language) * 100 as defect_rate\nfrom(\n  select count(DISTINCT defect_id) as defect_num, institute, center_name, department\n  from target_defect_stat_pos, target_pos, user_pos\n  where target_defect_stat_pos.target_id = target_pos.id and target_pos.owner = user_pos.id and institute='$institute' and center_name='$center_name'\n  group by institute, center_name,department\n) as defect_num_of_inst,(\n  select department, sum(defect_num_of_language)+119 as sum_num_of_language\n  from(\n    select DISTINCT case when language = 'C' or language = 'C++' then 'C&C++' else language end as language, department\n    from target_pos, user_pos\n    where target_pos.owner = user_pos.id and institute='$institute' and center_name='$center_name'\n  ) as language_in_department, (\n    select language,count(defect_id) as defect_num_of_language\n    from defect_pos\n    group by language\n  ) as defect_stat_of_language\n  where language_in_department.language=defect_stat_of_language.language\n  group by department\n) as all_num_of_inst\nwhere defect_num_of_inst.department=all_num_of_inst.department\norder by defect_rate desc"
    }
   ]
  },
  {
   "title": "${department}靶标缺陷覆盖率",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "select defect_num_of_inst.institute, defect_num_of_inst.center_name, defect_num_of_inst.department, defect_num_of_inst.name as target_name, language, (defect_num_of_inst.defect_num/sum_num_of_language) * 100 as defect_rate\nfrom(\n  select count(DISTINCT defect_id) as defect_num, institute, center_name,department, target_pos.name as name, target_pos.language as language\n  from target_defect_stat_pos, target_pos, user_pos\n  where target_defect_stat_pos.target_id = target_pos.id and target_pos.owner = user_pos.id \n  and institute='$institute' and center_name='$center_name' and department='$department'\n  group by institute, center_name,department, target_pos.name, target_pos.language\n) as defect_num_of_inst,(\n  select language_in_target_name.name as name, sum(defect_num_of_language)+119 as sum_num_of_language\n  from(\n    select DISTINCT case when language = 'C' or language = 'C++' then 'C&C++' else language end as language, target_pos.name as name\n    from target_pos, user_pos\n    where target_pos.owner = user_pos.id and institute='$institute' and center_name='$center_name' and department='$department'\n  ) as language_in_target_name, (\n    select language,count(defect_id) as defect_num_of_language\n    from defect_pos\n    group by language\n  ) as defect_stat_of_language\n  where language_in_target_name.language=defect_stat_of_language.language\n  group by language_in_target_name.name\n) as all_num_of_inst\nwhere defect_num_of_inst.name=all_num_of_inst.name\norder by defect_rate desc"
    }
   ]
  },
  {
   "title": "${target_name}靶标规范覆盖情况",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "select defect_pos.defect_class, defect_pos.defect_subclass, defect_pos.defect_describe, \ncase when defect_num isnull then 0 else defect_num end as defect_thick from (\n  select * \n  from defect_pos \n  where language='C&C++' or language='通用'\n)defect_pos left outer join (select * from target_defect_stat_pos \n  where target_defect_stat_pos.target_id in (\n    select target_pos.id\n    from target_pos, user_pos\n    where target_pos.owner=user_pos.id and user_pos.institute='$institute' and user_pos.center_name='$center_name'\n    and user_pos.department='$department' and target_pos.name='$target_name'\n  )\n)target_defect_stat_pos \non defect_pos.defect_id=target_defect_stat_pos.defect_id\norder by defect_thick desc"
    }
   ]
  }
 ]
}